### ISSUE TITLE
📐Missing triangles on receive

### ISSUE THREAD

**Issue by oguzhankoral** [specklesystems/speckle-sketchup#140]
For some rare cases upcoming meshes created in a bad way on receive. It's a edge case.

![Untitled](https://user-images.githubusercontent.com/45078678/212876421-c39b2b38-fc6e-4ffb-bcdd-3394385d20f5.png)

![Untitled (1)](https://user-images.githubusercontent.com/45078678/212876517-e7bacba2-cce7-4c7f-87df-ac40ae3cc7d9.png)

![Untitled (2)](https://user-images.githubusercontent.com/45078678/212876530-62539158-691e-41c6-845e-f6d01c691b51.png)

**Comment by bimgeek** [comment]
This is fixed with the 2.17 release.
