### ISSUE TITLE
🐛 Bug: Receiving Large models from Revit

### ISSUE THREAD

**Issue by oguzhankoral** [specklesystems/speckle-sketchup#161]
This issue reported by community. See topic -> https://speckle.community/t/receiving-very-large-model-to-sketchup/4710

**Comment by oguzhankoral** [comment]
This is what happens behind the scene.
![image](https://user-images.githubusercontent.com/45078678/221130583-1107b5ea-acd4-450d-984f-1980c8b90bc0.png)

**Comment by paloknapo** [comment]
Closing as it is related to https://github.com/specklesystems/speckle-server/issues/1415
