### ISSUE TITLE
speckle-sketchup on macos

### ISSUE THREAD

**Issue by ruggieroguida** [specklesystems/speckle-sketchup#18]
First of all, amazing work with Speckle. I love what you guys are doing.

I was installing speckle-sketchup on macos and found the following issue. 

I have first built and installed the plugin following the instructions [here](https://speckle.guide/user/sketchup.html).
When you launch the speckle connector you get the following error
```
Launching Speckle Connector from /Users/ruggiero/Library/Application Support/SketchUp 2021/SketchUp/Plugins/speckle_connector/html/index.html
Error: #<IOError: No Speckle Directory exists. Please read the guide to get Speckle set up on your machine: 
https://speckle.guide/user/manager.html>
/Users/ruggiero/Library/Application Support/SketchUp 2021/SketchUp/Plugins/speckle_connector/accounts.rb:51:in `_get_speckle_dir'
/Users/ruggiero/Library/Application Support/SketchUp 2021/SketchUp/Plugins/speckle_connector/accounts.rb:15:in `load_accounts'
/Users/ruggiero/Library/Application Support/SketchUp 2021/SketchUp/Plugins/speckle_connector/dialog.rb:84:in `init_local_accounts'
/Users/ruggiero/Library/Application Support/SketchUp 2021/SketchUp/Plugins/speckle_connector/dialog.rb:42:in `block in show_dialog'
```

This is caused by the way the platform is identified in `accounts.rb`. In Sketchup for macos `RUBY_PLATFORM.downcase` returns `x86_64-darwin18` and this contains `win`.

According to [this](https://ruby.sketchup.com/Sketchup.html#platform-class_method) a better way to check for the platform is to use `Sketchup.platform` replacing the function with something like this:

```
    def self._get_speckle_dir
      # platform = RUBY_PLATFORM.downcase
      
      speckle_dir =
        if Sketchup.platform == :platform_win
          # win
          File.join(Dir.home, "AppData/Roaming/Speckle")
        elsif Sketchup.platform == :platform_osx
          # mac
          File.join(Dir.home, ".config", "Speckle")
        else
          # linux
          # Do you need this?
          File.expand_path("~/.local/share/Speckle")
        end
      return speckle_dir if Dir.exist?(speckle_dir)

      raise(IOError, "No Speckle Directory exists. Please read the guide to get Speckle set up on your machine: \nhttps://speckle.guide/user/manager.html")
    end

```
Tested on my mac and it works.

Hope this helps

**Comment by izzylys** [comment]
Hi @ruggieroguida,

Thanks so much for spotting this and providing a fix! I don't use or have a Mac to test this against so I honestly wasn't sure how this would work out on MacOS. I appreciate your trying it out and filing this issue.

I'll do a quick test to double check that it's all still fine and dandy on windows, then will push out a fix asap!
