### ISSUE TITLE
Improve (in)validation of speckle entities

### ISSUE THREAD

**Issue by oguzhankoral** [specklesystems/speckle-sketchup#257]
Once we received objects and started to track them with `SpeckleEntity` objects, we need to improve our validation and invalidation of the objects with better observer track. This will improve our update behavior dramatically. Currently this process is done for only pushpull tool changes for tests purposes before. But we need to consider other interactions that triggered with observers.

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
