### ISSUE TITLE
🗳️ Check clearing localStorage caches are needed for UI

### ISSUE THREAD

**Issue by oguzhankoral** [specklesystems/speckle-sketchup#263]
Discussion started with the forum reporting https://speckle.community/t/list-of-streams-missing-on-sketchup/5558.
A user faced with this issue who uses before local server on computer but not anymore. Somehow we need to check valid servers on the localStorage before initializing UI.

**Comment by bimgeek** [comment]
Closing this ticket as we are moving to Jira to reduce noise. You can access it there.
