### ISSUE TITLE
🔢 Map objects according to selected objects geometric state

### ISSUE THREAD

**Issue by oguzhankoral** [specklesystems/speckle-sketchup#273]
Add support for the conversion of Sketchup faces to Floors, Ceiling, Roof, Wall, Topography in Revit.
Geometries should be detected as horizontal, vertical or slanted to be able to assign correct mapping method.

- [x] Floor #289 
- [x] Default Floor #285 
- [x] Wall #294 
- [x] Default Wall #294
- [ ] Ceiling
- [ ] Default Ceiling
- [ ] Roof
- [ ] Default Roof
- [ ] Column
- [ ] Default Column
- [ ] Beam
- [ ] Default Beam

**Comment by bimgeek** [comment]
Closing this ticket as we are already tracking the Mapper issues separately.
