### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-sketchup#4]
- [x] open in web
- [x] add commit message
- [x] switch branches
- [ ] ~create streams~
- [ ] ~create branches~
- [x] search streams

somewhat align with desktopui 2

**Comment by teocomi** [comment]
I don't think we need to let ppl create branches and streams form the main UI at this stage, it's not even possible in dui2 :)

**Comment by izzylys** [comment]
closed w #22
