### ISSUE TITLE
⚙ Advanced Settings

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-sketchup#55]
### Description

Include `Advanced Settings` option in the DUI Makeover.

- [x] Dark/Light Mode

#### Send Options
- [x] Combines faces by materials
- [x] Include entity attributes

#### Receive Options
- [x] Merge co-planar faces on receive

#### Optional: Affected Projects

Issue #52

**Comment by oguzhankoral** [comment]
@bimgeek Can you update issue description with up-to-date ones

**Comment by bimgeek** [comment]
> @bimgeek Can you update issue description with up-to-date ones

updated.

**Comment by bimgeek** [comment]
Implemented with 2.11
