### ISSUE TITLE
🤝 Merge Coplanar Faces

### ISSUE THREAD

**Issue by bimgeek** [specklesystems/speckle-sketchup#56]
### Expected vs. Actual Behavior

Simple shapes comes as triangles. Lets merge them and get single faces.

![image](https://user-images.githubusercontent.com/51519350/179961835-77542667-5dfa-4991-b421-15fedfb51018.png)
Ugly Triangles📐

![image](https://user-images.githubusercontent.com/51519350/179961990-c716d11f-a89a-4f2f-813c-5e1eeb800a76.png)
Beautiful Faces🔳

### Workaround
Currently I use `Cleanup` plugin to clean those kind of edges/faces👇.

https://extensions.sketchup.com/extension/046175e5-a87a-4254-9329-1accc37a5e21/clean-up

![image](https://user-images.githubusercontent.com/51519350/179962445-936bc1ab-290d-4dd3-8673-bcc17ce9eff5.png)

### Proposed Solution (if any)

Do a merge operation after receiving geometry.

edit from @izzylys: should add an option in #55 to toggle on/off this behaviour as it might not always be desirable (since you're turning triangulated meshes into ngon meshes)

**Comment by oguzhankoral** [comment]
@bimgeek I could not reproduce this issue. In which direction you are facing with this issue? From which connector to SketchUp? Can you please provide me steps to reproduce this attitude?

**Comment by bimgeek** [comment]
Hi @oguzhankoral,

here are the steps to reproduce this issue.

- open speckle connector in sketchup and receive this stream (i added you as collab) 👉: [https://speckle.xyz/streams/b623a319f4](https://speckle.xyz/streams/b623a319f4)
- After geometry received, go to `View` and enable `Hidden Geometry`. Now you should be able to see the mesh edges.

here is a GIF of the above steps👇:

![SketchUp_fjxMEFp25X](https://user-images.githubusercontent.com/51519350/184085228-56b2109c-9941-47a1-ba1d-fa60d2544369.gif)

Sketchup file with ugly edges 👇:

[OguzhanTest.zip](https://github.com/specklesystems/speckle-sketchup/files/9306969/OguzhanTest.zip)

**Comment by izzylys** [comment]
@oguzhankoral to elaborate, this is definitely an issue from any speckle connector that doesn't support ngons (or from receiving any triangulated mesh). on receive into sketchup, interior edges are smoothed/hidden which is purely a view setting ie the geometry is not altered. each poly in a received mesh is converted into a sketchup face which @bimgeek demonstrated you can show by manually turning on hidden geometry.
