### ISSUE TITLE
Alpha Release

### ISSUE THREAD

**Issue by teocomi** [specklesystems/speckle-sketchup#6]
Let's try release this sprint!

- [ ] Finalize alpha for wider announcement 
- [ ] Create basic set of docs / tutorials

**Comment by izzylys** [comment]
done!
[docs](https://speckle.guide/user/sketchup.html), [tutorial](https://speckle.systems/tutorials/sketchup-alpha/), & [forum](https://speckle.community/t/speckle-sketchup-connector-alpha/1980)
